### ISSUE TITLE
What is the "Z" in your equa 10

### ISSUE THREAD

**Issue by junleiz** [clovaai/overhaul-distillation#15]
![image](https://user-images.githubusercontent.com/26025961/70680692-ec846c00-1cd3-11ea-8cd3-05b4e9ee722f.png)
Hello, could you please tell me what is the Z in equ10? Thanks

**Comment by bhheo** [comment]
Hi

Before starting explanation, I just found a minor error on equ (9).
In equ (9), sigma should be out of sqrt operation, because it is gaussian distribution.
<img width="365" alt="스크린샷 2019-12-12 오후 1 06 36" src="https://user-images.githubusercontent.com/8871141/70681868-4428d480-1ce0-11ea-89ed-3c3ba003c754.png">
I'm sorry about that. But, it is only error on equ (9) and equ (10) is correct.

---

The Z is normalizing constant.
Since the margin is expectation value over negative responses, conceptual form of equ (9) is
<img width="263" alt="스크린샷 2019-12-12 오후 1 16 39" src="https://user-images.githubusercontent.com/8871141/70682264-a7673680-1ce1-11ea-9e32-46eae5566dff.png">

The Z is denominator
<img width="641" alt="스크린샷 2019-12-12 오후 1 20 04" src="https://user-images.githubusercontent.com/8871141/70682402-20ff2480-1ce2-11ea-8c71-b55780a25259.png">

Numerator value is calculated as
<img width="551" alt="스크린샷 2019-12-12 오후 1 23 58" src="https://user-images.githubusercontent.com/8871141/70682581-abe01f00-1ce2-11ea-84c5-e664044f935d.png">

Combining these two values become equ (10)
<img width="295" alt="스크린샷 2019-12-12 오후 1 24 55" src="https://user-images.githubusercontent.com/8871141/70682635-d336ec00-1ce2-11ea-88ed-d7294cd3cf20.png">
