### ISSUE TITLE
Normalization factor Z in margin value

### ISSUE THREAD

**Issue by winycg** [clovaai/overhaul-distillation#18]
Very interesting work for feature distillation.! I would like to know why Z is needed in expectation calculation of negative responses. So if we discard  Z, I want to know whether the performance is degraded.  Thank you!

**Comment by bhheo** [comment]
Hi, thank you for your interest on my work.

Because I want to use expectation over conditional situation (x < 0), Z is needed to calibrate original distribution to distribution only on negative parts.
However, in experiments with various margin, I found that my method is not very sensitive to margin value.
So, I think discarding Z doesn't make significant performance changes.

But, I didn't measure performance without Z.
So, I don't know exactly whether it degrades performance or not.

**Comment by winycg** [comment]
Thanks for your response！ I get it.
