### ISSUE TITLE
low speed when training the network

### ISSUE THREAD

**Issue by PkuDavidGuan** [clovaai/overhaul-distillation#24]
Hi,
    thanks for your nice code. When I use the ImageNet training code, I found the speed is really slow. To be specific, the model will wait for 2 minutes for data loading in every 20 batches or so. The environment has 4 1080Ti GPUs, 16 CPUs and 90 G memory, and I set the num_workers of the dataloader to 16, the batch size is 512. Is there any good advice for a fast training?
<img width="604" alt="training" src="https://user-images.githubusercontent.com/18279248/89011256-a0f5ff80-d342-11ea-90d9-76434ea03fd2.png">

**Comment by PkuDavidGuan** [comment]
In the illustration, I made a log in each 10 batches. I think a normal training time for 10 batches should be 3 seconds.

**Comment by bhheo** [comment]
Hi

I think it is because of the dataloader that training stops in a specific batch
Here is the solution I think:

1. Putting data on SSD
The speed difference between SSDs and HDDs is quite large, and SSDs often solve most dataloader problems

2. Use recent torch loader
The recent torch includes dataloader using prefetch function by default, which helps to reduce data loading time.

3. Use [NVIDIA/DALI](https://github.com/NVIDIA/DALI) loader
It is much faster and powerful than torch dataloader. But, it requires code revision.

4. Change dataloader setting
It is not a fundamental solution, but it is possible to improve the speed by adjusting dataloader settings
Just try large `num_worker`, small `batch_size` and large `prefetch_factor`
But, it might not solve 2 minutes waiting problem

I think these might solve the problem.
