### ISSUE TITLE
ResNet18/34

### ISSUE THREAD

**Issue by gadhane** [clovaai/overhaul-distillation#40]
I tried to use ResNet18/34 instead of ResNet50, and can't it rises this error. It works fine for ResNet50, but not for 18/34. Any suggestions how to solve this error please. `RuntimeError: Given groups=1, weight of size [256, 256, 1, 1], expected input[5, 64, 56, 56] to have 256 channels, but got 64 channels instead`

**Comment by bhheo** [comment]
Hi

Because my code is not implemented for ResNet18 or ResNet34, it might cause errors.
I'm not sure solving the current error can make the code works for ResNet 18 / 34.

Anyway, I think your error made by this lines

https://github.com/clovaai/overhaul-distillation/blob/76344a84a7ce23c894f41a2e05b866c9b73fd85a/ImageNet/models/ResNet.py#L174-L176

I didn't consider ResNet with basic blocks. It returns channel size of bottleneck block.
So, you have to put a channel setting of BasicBlock ResNet such as ResNet18 & 34.
For example
```python
    def get_channel_num(self):
        if isinstance(self.layer1[0], Bottleneck):
            return [256, 512, 1024, 2048]
        elif isinstance(self.layer1[0], BasicBlock):
            return [64, 128, 256, 512]
        else:
            raise NotImplementedError
```

I hope it helps you to run the code for your setting.

**Comment by gadhane** [comment]
Thank you so much, this actually solved the issue.
